CREATE SCHEMA `users`;

USE `users`;

CREATE TABLE user_type (
	id INT NOT NULL PRIMARY KEY,
    rol VARCHAR(10) NOT NULL
);

CREATE TABLE client (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	first_name VARCHAR(50) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    rol INT,
    sex TINYINT,
    user_status TINYINT,
    FOREIGN KEY (rol) REFERENCES user_type(id) ON DELETE CASCADE ON UPDATE CASCADE
);


